# Lab Excercise 1

In [7]:
# importing numpy

import numpy as np

In [32]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.

a = np.array([1,2,3,4,5,0])
print("Test if all elements of a are non-zero: ", a.all())
    
    


Test if all elements of a are non-zero:  False


In [31]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.

b = np.array([0,0,0,0])
print("Test if any elements of b are non-zero: ", b.any())



Test if all elements of b are non-zero:  False


In [23]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.

c = np.array([56, -2, 7])
print("The array is", c)
print("Item size of array c is: ", c.itemsize)   # c.itemsize: the size in bits of each element of the array.
print("Memory size of a is: ", c.itemsize*c.size, "bits")   # c.itemsize: size of the array in bits.

The array is [56 -2  7]
Item size of array c is:  8
Memory size of a is:  24 bits


In [24]:
# Create a numpy array with 10 zeros and print the array.
arr_zeroes = np.zeros(10)
print(arr_zeroes)
# Create a numpy array with 6 ones and print the array.
arr_ones = np.ones(6)
print(arr_ones)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
arr_threes = np.full(12,3)
print(arr_threes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [27]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr_8to20 = np.arange(8,21,4)
print(arr_8to20)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr_even = np.arange(8,21,2)
print(arr_even)

[ 8 12 16 20]
[ 8 10 12 14 16 18 20]


In [112]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean = 2
std = 0.5
sizeArray = 100
random_array = np.random.normal(mean, std, sizeArray)
print("The mean is", np.mean(random_array))
print("The standard deviation is", np.std(random_array))
print("The size of the array is", np.size(random_array))
print("The max element in the array is: ", random_array.max())
print("The min element in the array is: ", random_array.min())

print()
print()

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

mean = 2
std = 0.5
sizeArray = 1000
random_array_2 = np.random.normal(mean, std, sizeArray)
print("The mean is", np.mean(random_array_2))
print("The standard deviation is", np.std(random_array_2))
print("The size of the array is", np.size(random_array_2))
print("The max element in the array is: ", random_array_2.max())
print("The min element in the array is: ", random_array_2.min())


# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

print()
print()


mean = 2
std = 0.5
sizeArray = 1000000
random_array_3 = np.random.normal(mean, std, sizeArray)
print("The mean is", np.mean(random_array_3))
print("The standard deviation is", np.std(random_array_3))
print("The size of the array is", np.size(random_array_3))
print("The max element in the array is: ", random_array_3.max())
print("The min element in the array is: ", random_array_3.min())

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?

print()
print()

print('''1. Sample Size and Mean:
Consistency: As the sample size increases, the sample mean tends to get closer to the theoretical mean of the normal distribution. This is due to the Law of Large Numbers, which states that as the number of observations increases, the sample mean will converge to the true mean.
Example Observation: With smaller sample sizes (e.g., 1,000 or 5,000), you might see the sample mean varying more from the theoretical mean (e.g., 2). With larger sample sizes (e.g., 10,000), the sample mean will generally be closer to 2.
2. Sample Size and Standard Deviation:
Consistency: Similarly, the sample standard deviation will approximate the theoretical standard deviation (e.g., 0.5) more closely as the sample size increases. This is also influenced by the Law of Large Numbers, which ensures that the sample standard deviation gets closer to the population standard deviation with larger samples.
Example Observation: For smaller sample sizes, the sample standard deviation might show more variation from the theoretical standard deviation. As the sample size grows, the sample standard deviation will more closely match the theoretical standard deviation.''')

The mean is 2.0126783233007814
The standard deviation is 0.48270845647737914
The size of the array is 100
The max element in the array is:  3.2982824965606117
The min element in the array is:  0.8478725814035359


The mean is 2.0068505327130075
The standard deviation is 0.5128387873835273
The size of the array is 1000
The max element in the array is:  3.5211429783956634
The min element in the array is:  0.16935268971520756


The mean is 2.000312362279965
The standard deviation is 0.49989186483185805
The size of the array is 1000000
The max element in the array is:  4.302225692915572
The min element in the array is:  -0.718658838986074
1. Sample Size and Mean:
Consistency: As the sample size increases, the sample mean tends to get closer to the theoretical mean of the normal distribution. This is due to the Law of Large Numbers, which states that as the number of observations increases, the sample mean will converge to the true mean.
Example Observation: With smaller sample sizes (e.g.,